/**
 * @file witnesses.ts
 * @author Ricardo Rius
 * @license GPL-3.0
 *
 * Copyright (C) 2025 Ricardo Rius
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 *
 * DISCLAIMER: This software is provided "as is" without any warranty.
 * Use at your own risk. The author assumes no responsibility for any
 * damages or losses arising from the use of this software.
 */

import {
  Contract as ContractType,
  Witnesses
} from "./managed/kitties/contract/index.js";

import { WitnessContext } from "@midnight-ntwrk/compact-runtime";

export type Contract<T, W extends Witnesses<T> = Witnesses<T>> = ContractType<
  T,
  W
>;

// The private state holds a per-user secret key (32 random bytes) generated by
// the DApp. The contract derives a stable account identifier from it on-chain
// (persistentHash of the secret), which is what gets stored and checked for
// ownership. The raw secret never leaves the DApp and is never written to the
// ledger, so a user proves ownership by knowing the secret rather than by
// presenting a public key that anyone could copy.
//
// The same secret backs two witnesses: `wit_NonFungibleTokenSK`, declared by
// the imported OpenZeppelin NonFungibleToken module and used by its mint,
// transfer, and approval circuits, and `localSecretKey`, declared by the
// kitties contract for its own circuits (breeding and sale authorization).
// Both derive the account id with the same library helper, so they MUST return
// the same secret; otherwise the module and the kitty circuits would see the
// caller as two different accounts.
//
// OpenZeppelin ships witness implementations only as test doubles and does not
// publish them; consumers are expected to author their own, as done here.
export type KittiesPrivateState = {
  readonly secretKey: Uint8Array;
};

export function createKittiesPrivateState(secretKey: Uint8Array): KittiesPrivateState {
  return { secretKey };
}

export const witnesses = {
  createRandomNumber: ({
    privateState
  }: WitnessContext<any, KittiesPrivateState>): [
    KittiesPrivateState,
    Uint8Array
  ] => {
    // Generate 32 random bytes using Math.random()
    const randomBytes = new Uint8Array(32);
    for (let i = 0; i < 32; i++) {
      randomBytes[i] = Math.floor(Math.random() * 256);
    }
    return [privateState, randomBytes];
  },

  // Returns the caller's secret key from private state for the kitty-specific
  // circuits. The contract hashes it into an account identifier; the secret
  // itself is never disclosed on-chain.
  localSecretKey: ({
    privateState
  }: WitnessContext<any, KittiesPrivateState>): [
    KittiesPrivateState,
    Uint8Array
  ] => [privateState, privateState.secretKey],

  // Returns the caller's secret key for the OpenZeppelin NonFungibleToken
  // module's circuits. Must return the same secret as localSecretKey so both
  // derive the same account id.
  wit_NonFungibleTokenSK: ({
    privateState
  }: WitnessContext<any, KittiesPrivateState>): [
    KittiesPrivateState,
    Uint8Array
  ] => [privateState, privateState.secretKey]
};
